---
- hosts: router
  connection: network_cli
  become: true
  gather_facts: no
  tasks:

  - name: Change hostname of router
    ios_config:
      lines:
        - hostname rio
    become: yes
    become_method: enable
    timeout: 60

  - name: service password-encryption on router
    ios_config:
      lines:
        - service password-encryption
    become: yes
    become_method: enable
    timeout: 60

  - name: Configure banner motd of router
    ios_banner:
      banner: login
      text: |
        Access prohibited, authorized personnel only.
    become: yes
    become_method: enable
    timeout: 60

  - name: Configure line console 0
    ios_config:
      lines:
        - password rio
        - login
      parents: line console 0
    become: yes
    become_method: enable
    timeout: 60
  - name: enable secret password on router
    ios_config:
      lines:
        - enable secret rio
    become: yes
    become_method: enable

  - name: Configure ip address of port g0/1 on router
    ios_config:
      lines:
        - ip address 10.0.0.118 255.255.255.0
        - no shutdown
      parents: interface g0/1
    become: yes
    become_method: enable

  - name: saving configuration on router
    ios_config:
      lines:
        - do write memory
    become: yes
    become_method: enable
